# Generated by Django 4.2.2 on 2023-06-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_profile_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_description', models.TextField()),
                ('book_price', models.IntegerField()),
                ('book_img', models.ImageField(upload_to='')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.author')),
            ],
        ),
    ]
