# Generated by Django 4.2.2 on 2023-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
